"""Central configuration for the KINESYS project."""

from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent

APP_NAME = "KINESYS"
APP_VERSION = "0.1.0"
MAIN_WINDOW_NAME = "KINESYS Foundation"

LOG_LEVEL = "INFO"
LOG_FORMAT = "%(asctime)s | %(levelname)s | %(name)s | %(message)s"

SMOOTHING_ALPHA = 0.4
FATIGUE_ALPHA = 0.7
CLICK_DEBOUNCE_MS = 500
SCROLL_SPEED = 3
PINCH_THRESHOLD = 30
ZOOM_THRESHOLD = 40
FATIGUE_THRESHOLD = 0.15
FATIGUE_WINDOW_FRAMES = 30
FATIGUE_DURATION_SECONDS = 5
ACTION_CONFIDENCE_THRESHOLD = 0.75
GESTURE_HOLD_FRAMES = 3
TERMINATION_HOLD_FRAMES = 6
KNN_SAMPLES_REQUIRED = 5
KNN_K = 3
CANVAS_SIZE = 280
CHAR_SIZE = 28
WRITE_CONFIDENCE_THRESHOLD = 0.70
PAUSE_THRESHOLD = 0.8
KEYBOARD_HOVER_SECONDS = 1.0
AIR_WRITER_STROKE_THICKNESS = 12
AIR_WRITER_STATIONARY_DISTANCE = 6
AIR_WRITER_MIN_DRAW_DISTANCE = 3
AIR_WRITER_MIN_PIXELS = 64
AIR_WRITER_PADDING = 12
RECENT_CHARS_LIMIT = 8
RECOGNIZED_TEXT_PREVIEW_LENGTH = 24
FPS_TARGET = 30
WEBCAM_WIDTH = 640
WEBCAM_HEIGHT = 480
DASHBOARD_REFRESH_MS = 50
DASHBOARD_SNAPSHOT_INTERVAL_SECONDS = 0.25
DASHBOARD_PORT = 8501
DASHBOARD_HOST = "127.0.0.1"
DASHBOARD_HEADLESS = "true"
DASHBOARD_SCRIPT = str(BASE_DIR / "ui" / "dashboard.py")
DASHBOARD_STATE_SNAPSHOT = str(BASE_DIR / "ui" / "dashboard_state.json")
DASHBOARD_STATE_HOST = "127.0.0.1"
DASHBOARD_STATE_PORT = 8765
DASHBOARD_STATE_AUTHKEY = "kinesys_dashboard_state"
DASHBOARD_STATE_ENV_HOST = "KINESYS_SHARED_STATE_HOST"
DASHBOARD_STATE_ENV_PORT = "KINESYS_SHARED_STATE_PORT"
DASHBOARD_STATE_ENV_AUTHKEY = "KINESYS_SHARED_STATE_AUTHKEY"
NGROK_AUTH_TOKEN_ENV = "NGROK_AUTH_TOKEN"
TRAINER_RECORD_INTERVAL_SECONDS = 0.4
DEMO_VIDEO_FILE = str(BASE_DIR / "demo_assets" / "demo_session.mp4")
DEMO_METADATA_FILE = str(BASE_DIR / "demo_assets" / "demo_session.json")
DEMO_WINDOW_NAME = "KINESYS Demo Playback"
DEMO_FPS_FALLBACK = 30.0
KEYBOARD_WINDOW_WIDTH = 920
KEYBOARD_WINDOW_HEIGHT = 320
KEYBOARD_WINDOW_POS_X = 40
KEYBOARD_WINDOW_POS_Y = 40
KEYBOARD_UI_POLL_MS = 50
KEYBOARD_BUTTON_PADX = 6
KEYBOARD_BUTTON_PADY = 6
KEYBOARD_FONT_SIZE = 16
EMNIST_BATCH_SIZE = 128
EMNIST_EPOCHS = 3
EMNIST_SHUFFLE_BUFFER = 4096
EMNIST_CLASS_COUNT = 26
EMNIST_INPUT_CHANNELS = 1
EMNIST_CONV1_FILTERS = 32
EMNIST_CONV2_FILTERS = 64
EMNIST_KERNEL_SIZE = 3
EMNIST_DENSE_UNITS = 128
EMNIST_DROPOUT = 0.25
EMNIST_DATASET_NAME = "emnist/letters"
EMNIST_TRAIN_SPLIT = "train[:90%]"
EMNIST_VALIDATION_SPLIT = "train[90%:]"
EMNIST_TEST_SPLIT = "test"
GESTURE_HISTORY_FRAMES = 12
SWIPE_HORIZONTAL_THRESHOLD = 55
SWIPE_VERTICAL_THRESHOLD = 45
FOUR_FINGER_SWIPE_THRESHOLD = 70
PEACE_FINGER_SPREAD_THRESHOLD = 30
CIRCLE_MIN_WIDTH = 40
CIRCLE_MIN_HEIGHT = 40
CIRCLE_MAX_START_END_DISTANCE = 50
CIRCLE_MIN_PATH_LENGTH = 220
ZOOM_DISTANCE_DELTA_THRESHOLD = 10
TERMINATION_INDEX_DISTANCE_THRESHOLD = 140
TERMINATION_VERTICAL_ALIGNMENT_THRESHOLD = 100
TERMINATION_POINTING_MARGIN = 8
SCROLL_DELTA_DIVISOR = 6
SCROLL_MIN_STEP = 1
MACRO_STATE_DURATION_SECONDS = 0.6
ACTION_RESET_GRACE_SECONDS = 0.4
FATIGUE_ALERT_COOLDOWN_SECONDS = 10.0
FATIGUE_SCORE_SCALE = 10.0
TRAINER_MIN_SAMPLES_TO_PREDICT = 3
TRAINER_SUPPORTED_GESTURES = (
    "INDEX_POINT",
    "PINCH",
    "PEACE_SIGN",
    "TWO_FINGER_SWIPE",
    "THREE_FINGER_LEFT",
    "THREE_FINGER_RIGHT",
    "FOUR_FINGER_SWIPE",
    "PINCH_ZOOM_IN",
    "PINCH_ZOOM_OUT",
    "CIRCLE",
    "CLOSED_FIST",
    "OPEN_PALM",
)

PROFILES_DIR = str(BASE_DIR / "profiles")
MODELS_DIR = str(BASE_DIR / "models")
ANALYTICS_LOG = str(BASE_DIR / "analytics.json")
MACROS_FILE = str(BASE_DIR / "macros.json")
EMNIST_MODEL_FILE = str(BASE_DIR / "models" / "emnist_cnn.h5")
PERSONAL_MODEL_FILE = str(BASE_DIR / "models" / "personal_gestures.pkl")
DASHBOARD_DIR = str(BASE_DIR / "ui")
KEYBOARD_WINDOW_TITLE = "KINESYS Keyboard"
KEYBOARD_LAYOUT_ROWS = (
    ("Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P"),
    ("A", "S", "D", "F", "G", "H", "J", "K", "L"),
    ("Z", "X", "C", "V", "B", "N", "M"),
    ("SPACE", "BACKSPACE"),
)

FOUNDATION_CAMERA_INDEX = 0
FOUNDATION_CAMERA_BACKEND = "CAP_DSHOW"
WEBCAM_FOURCC = "MJPG"
WEBCAM_CHANNELS = 3
FRAME_FLIP_CODE = 1
FRAME_WAIT_KEY_MS = 1
FRAME_ENCODE_EXTENSION = ".jpg"
FRAME_JPEG_QUALITY = 80
EXIT_KEY = "q"

MAX_HANDS = 2
HAND_LANDMARK_COUNT = 21
LANDMARK_VECTOR_LENGTH = 63
MIN_DETECTION_CONFIDENCE = 0.6
MIN_TRACKING_CONFIDENCE = 0.6

WRIST_ID = 0
THUMB_TIP_ID = 4
THUMB_IP_ID = 3
INDEX_FINGER_PIP_ID = 6
INDEX_FINGER_DIP_ID = 7
INDEX_FINGER_TIP_ID = 8
MIDDLE_FINGER_PIP_ID = 10
MIDDLE_FINGER_TIP_ID = 12
RING_FINGER_PIP_ID = 14
RING_FINGER_TIP_ID = 16
PINKY_PIP_ID = 18
PINKY_TIP_ID = 20

HUD_MARGIN_X = 16
HUD_MARGIN_Y = 30
HUD_LINE_HEIGHT = 28
HUD_FONT_SCALE = 0.7
HUD_FONT_THICKNESS = 2
HUD_TEXT_COLOR = (255, 255, 255)
HUD_STATE_COLOR = (15, 110, 86)
HUD_WARNING_COLOR = (113, 43, 19)
HUD_PANEL_COLOR = (0, 0, 0)
HUD_PANEL_ALPHA = 0.45
CURSOR_INDICATOR_RADIUS = 12
CURSOR_INDICATOR_COLOR = (15, 110, 86)
CURSOR_INDICATOR_THICKNESS = 2
TEXT_SHADOW_OFFSET_X = 2
TEXT_SHADOW_OFFSET_Y = 2
TEXT_SHADOW_COLOR = (0, 0, 0)

PYAUTOGUI_PAUSE = 0.0
PYAUTOGUI_MINIMUM_DURATION = 0.0
PYAUTOGUI_MINIMUM_SLEEP = 0.0
PYAUTOGUI_MOVE_DURATION = 0.0
PYAUTOGUI_FAILSAFE = True

PINCH_GESTURE_CONFIDENCE = 0.95
INDEX_GESTURE_CONFIDENCE = 0.90
OPEN_PALM_GESTURE_CONFIDENCE = 0.88
CLOSED_FIST_GESTURE_CONFIDENCE = 0.86
PEACE_SIGN_GESTURE_CONFIDENCE = 0.90
TWO_FINGER_SWIPE_GESTURE_CONFIDENCE = 0.86
THREE_FINGER_GESTURE_CONFIDENCE = 0.87
FOUR_FINGER_SWIPE_GESTURE_CONFIDENCE = 0.89
PINCH_ZOOM_GESTURE_CONFIDENCE = 0.91
CIRCLE_GESTURE_CONFIDENCE = 0.82
LEFT_MODIFIER_GESTURE_CONFIDENCE = 0.89
TERMINATION_GESTURE_CONFIDENCE = 0.96
UNKNOWN_GESTURE_CONFIDENCE = 0.0

GESTURE_UNKNOWN = "UNKNOWN"
GESTURE_INDEX_POINT = "INDEX_POINT"
GESTURE_PINCH = "PINCH"
GESTURE_PEACE_SIGN = "PEACE_SIGN"
GESTURE_TWO_FINGER_SWIPE = "TWO_FINGER_SWIPE"
GESTURE_THREE_FINGER_LEFT = "THREE_FINGER_LEFT"
GESTURE_THREE_FINGER_RIGHT = "THREE_FINGER_RIGHT"
GESTURE_FOUR_FINGER_SWIPE = "FOUR_FINGER_SWIPE"
GESTURE_PINCH_ZOOM_IN = "PINCH_ZOOM_IN"
GESTURE_PINCH_ZOOM_OUT = "PINCH_ZOOM_OUT"
GESTURE_CIRCLE = "CIRCLE"
GESTURE_OPEN_PALM = "OPEN_PALM"
GESTURE_CLOSED_FIST = "CLOSED_FIST"
GESTURE_TWO_HANDS_X = "TWO_HANDS_X"
GESTURE_OPEN_PALM_LEFT = "OPEN_PALM_LEFT"
GESTURE_INDEX_LEFT = "INDEX_LEFT"
GESTURE_PEACE_LEFT = "PEACE_LEFT"
GESTURE_THREE_FINGERS_LEFT = "THREE_FINGERS_LEFT"

HAND_RIGHT = "Right"
HAND_LEFT = "Left"
HAND_UNKNOWN = "Unknown"

STATE_IDLE = "IDLE"
STATE_CURSOR = "CURSOR"
STATE_WRITE = "WRITE"
STATE_SCROLL = "SCROLL"
STATE_MACRO = "MACRO"
STATE_LOCK = "LOCK"
STATE_TERMINATED = "TERMINATED"

MODIFIER_NONE = None
MODIFIER_CTRL = "CTRL"
MODIFIER_SHIFT = "SHIFT"
MODIFIER_ALT = "ALT"

KEY_CTRL = "ctrl"
KEY_SHIFT = "shift"
KEY_ALT = "alt"
KEY_TAB = "tab"
KEY_LEFT_ARROW = "left"
KEY_RIGHT_ARROW = "right"

REQUIRED_FOUNDATION_FILES = (
    BASE_DIR / "config.py",
    BASE_DIR / "check_setup.py",
    BASE_DIR / "hand_tracker.py",
    BASE_DIR / "cursor_controller.py",
    BASE_DIR / "main.py",
)

FOUNDATION_DEPENDENCIES = {
    "cv2": "opencv-python",
    "mediapipe": "mediapipe",
    "numpy": "numpy",
    "pyautogui": "pyautogui",
}

STRICT_DEPENDENCIES = {
    "pygetwindow": "pygetwindow",
    "psutil": "psutil",
    "pyttsx3": "pyttsx3",
    "sklearn": "scikit-learn",
    "streamlit": "streamlit",
    "tensorflow": "tensorflow",
}

STRICT_REQUIRED_FILES = (
    BASE_DIR / "models" / "emnist_cnn.h5",
)

SUPPORTED_PYTHON_MIN = (3, 10)
SUPPORTED_PYTHON_MAX = (3, 12)
