"""Central configuration for the KINESYS project."""

from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent

APP_NAME = "KINESYS"
APP_VERSION = "0.1.0"
MAIN_WINDOW_NAME = "KINESYS Foundation"

LOG_LEVEL = "INFO"
LOG_FORMAT = "%(asctime)s | %(levelname)s | %(name)s | %(message)s"

SMOOTHING_ALPHA = 0.4
FATIGUE_ALPHA = 0.7
CLICK_DEBOUNCE_MS = 500
SCROLL_SPEED = 3
PINCH_THRESHOLD = 30
ZOOM_THRESHOLD = 40
FATIGUE_THRESHOLD = 0.15
FATIGUE_WINDOW_FRAMES = 30
FATIGUE_DURATION_SECONDS = 5
ACTION_CONFIDENCE_THRESHOLD = 0.75
GESTURE_HOLD_FRAMES = 3
TERMINATION_HOLD_FRAMES = 6
KNN_SAMPLES_REQUIRED = 5
KNN_K = 3
CANVAS_SIZE = 280
CHAR_SIZE = 28
WRITE_CONFIDENCE_THRESHOLD = 0.70
PAUSE_THRESHOLD = 0.8
KEYBOARD_HOVER_SECONDS = 1.0
FPS_TARGET = 30
WEBCAM_WIDTH = 640
WEBCAM_HEIGHT = 480
DASHBOARD_REFRESH_MS = 50

PROFILES_DIR = str(BASE_DIR / "profiles")
MODELS_DIR = str(BASE_DIR / "models")
ANALYTICS_LOG = str(BASE_DIR / "analytics.json")
MACROS_FILE = str(BASE_DIR / "macros.json")
EMNIST_MODEL_FILE = str(BASE_DIR / "models" / "emnist_cnn.h5")
PERSONAL_MODEL_FILE = str(BASE_DIR / "models" / "personal_gestures.pkl")

FOUNDATION_CAMERA_INDEX = 0
FOUNDATION_CAMERA_BACKEND = "CAP_DSHOW"
WEBCAM_FOURCC = "MJPG"
WEBCAM_CHANNELS = 3
FRAME_FLIP_CODE = 1
FRAME_WAIT_KEY_MS = 1
FRAME_ENCODE_EXTENSION = ".jpg"
FRAME_JPEG_QUALITY = 80
EXIT_KEY = "q"

MAX_HANDS = 2
HAND_LANDMARK_COUNT = 21
LANDMARK_VECTOR_LENGTH = 63
MIN_DETECTION_CONFIDENCE = 0.6
MIN_TRACKING_CONFIDENCE = 0.6

WRIST_ID = 0
THUMB_TIP_ID = 4
THUMB_IP_ID = 3
INDEX_FINGER_PIP_ID = 6
INDEX_FINGER_DIP_ID = 7
INDEX_FINGER_TIP_ID = 8
MIDDLE_FINGER_PIP_ID = 10
MIDDLE_FINGER_TIP_ID = 12
RING_FINGER_PIP_ID = 14
RING_FINGER_TIP_ID = 16
PINKY_PIP_ID = 18
PINKY_TIP_ID = 20

HUD_MARGIN_X = 16
HUD_MARGIN_Y = 30
HUD_LINE_HEIGHT = 28
HUD_FONT_SCALE = 0.7
HUD_FONT_THICKNESS = 2
HUD_TEXT_COLOR = (255, 255, 255)
HUD_STATE_COLOR = (15, 110, 86)
HUD_WARNING_COLOR = (113, 43, 19)
HUD_PANEL_COLOR = (0, 0, 0)
HUD_PANEL_ALPHA = 0.45
CURSOR_INDICATOR_RADIUS = 12
CURSOR_INDICATOR_COLOR = (15, 110, 86)
CURSOR_INDICATOR_THICKNESS = 2
TEXT_SHADOW_OFFSET_X = 2
TEXT_SHADOW_OFFSET_Y = 2
TEXT_SHADOW_COLOR = (0, 0, 0)

PYAUTOGUI_PAUSE = 0.0
PYAUTOGUI_MINIMUM_DURATION = 0.0
PYAUTOGUI_MINIMUM_SLEEP = 0.0
PYAUTOGUI_MOVE_DURATION = 0.0
PYAUTOGUI_FAILSAFE = True

PINCH_GESTURE_CONFIDENCE = 0.95
INDEX_GESTURE_CONFIDENCE = 0.90
OPEN_PALM_GESTURE_CONFIDENCE = 0.88
CLOSED_FIST_GESTURE_CONFIDENCE = 0.86
UNKNOWN_GESTURE_CONFIDENCE = 0.0

GESTURE_UNKNOWN = "UNKNOWN"
GESTURE_INDEX_POINT = "INDEX_POINT"
GESTURE_PINCH = "PINCH"
GESTURE_OPEN_PALM = "OPEN_PALM"
GESTURE_CLOSED_FIST = "CLOSED_FIST"

HAND_RIGHT = "Right"
HAND_LEFT = "Left"
HAND_UNKNOWN = "Unknown"

STATE_IDLE = "IDLE"
STATE_CURSOR = "CURSOR"
STATE_WRITE = "WRITE"
STATE_SCROLL = "SCROLL"
STATE_MACRO = "MACRO"
STATE_LOCK = "LOCK"
STATE_TERMINATED = "TERMINATED"

MODIFIER_NONE = None

REQUIRED_FOUNDATION_FILES = (
    BASE_DIR / "config.py",
    BASE_DIR / "check_setup.py",
    BASE_DIR / "hand_tracker.py",
    BASE_DIR / "cursor_controller.py",
    BASE_DIR / "main.py",
)

FOUNDATION_DEPENDENCIES = {
    "cv2": "opencv-python",
    "mediapipe": "mediapipe",
    "numpy": "numpy",
    "pyautogui": "pyautogui",
}

STRICT_DEPENDENCIES = {
    "pygetwindow": "pygetwindow",
    "psutil": "psutil",
    "pyttsx3": "pyttsx3",
    "sklearn": "scikit-learn",
    "streamlit": "streamlit",
    "tensorflow": "tensorflow",
}

STRICT_REQUIRED_FILES = (
    BASE_DIR / "models" / "emnist_cnn.h5",
)

SUPPORTED_PYTHON_MIN = (3, 10)
SUPPORTED_PYTHON_MAX = (3, 12)
